### ISSUE TITLE
load_model(config.model_path) 

### ISSUE THREAD

**Issue by ksknysn** [mhmddpkts/Face-Recognition-with-FaceNet-and-OpenCV#1]
when program is running load_model(config.model_path) command,
i take the error:
\AppData\Local\Programs\Python\Python38\lib\site-packages\keras\utils\generic_utils.py", line 789, in func_load 
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by m-pektas** [comment]
hi @ksknysn , I run environment installation commands and main.py script now, I don't get any errors. Can you try following commands to install your environment before running main.py ?

```
conda create --name fr python=3.6.9 -y
pip install -r requirenments.txt
```

**Comment by ksknysn** [comment]
hi, this installation requires visual studio but i don't have it, nevertheless i tried to install it but i couldn't. anyway, i found other codes on github and try to implement them. by the way i would like to ask you a question: where can i find the newer models(facenet_keras.h5) that compiled on newer versions of keras, python etc. 
i will read your code to understand facenet. thank you a lot

https://www.python.org/downloads/release/python-369/

**Comment by m-pektas** [comment]
I don't understand, why you require visual studio. You need only anaconda for package management. you can use anaconda environment on any development editors.  By the way, If you want, You can use another package managing tool, don't have to use anaconda. Anyway, I don't have newer version of the model. This project was my hobby project almost 2 years ago and my reference blog post was "https://machinelearningmastery.com/how-to-develop-a-face-recognition-system-using-facenet-in-keras-and-an-svm-classifier/".  Thank you for your interest, sorry for I couldn't help you very well.

**Comment by ksknysn** [comment]
i tried it again and i have these issue.

(fr) C:\Users\--\facenet>python main.py
2021-10-31 18:58:56.869289: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2021-10-31 18:58:56.869843: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from  preprocess import Preprocess
  File "C:\Users\--\facenet\preprocess.py", line 10, in <module>
    from keras.models import load_model
  File "C:\Users\--\anaconda3\envs\fr\lib\site-packages\keras\__init__.py", line 25, in <module>
    from keras import models
  File "C:\Users\--\anaconda3\envs\fr\lib\site-packages\keras\models.py", line 19, in <module>
    from keras import backend
  File "C:\Users\--\anaconda3\envs\fr\lib\site-packages\keras\backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config'

**Comment by ksknysn** [comment]
I fixed this issue by upgrading tensorflow:
pip install --upgrade tensorflow
